### ISSUE TITLE
Proposal for having ARN as a standard key across all service assets being scanned for AWS

### ISSUE THREAD

**Issue by rams3sh** [nccgroup/ScoutSuite#511]
Currently different service in scoutsuite have different set of key (non-standard) attributes depending on the nature of service and the data required to identify a finding.

This issue proposes to have one more standard key  called 'arn'  containing the corresponding asset's arn value over and above already existing attributes for each and every service asset.  Some services do have arn as part of their attribute set, but not all. 

Example : 'iam' has arn for all of it's assets except credential report (which obviously would not make sense). But 'ec2' assets such as snapshots , security_groups etc does not have arn as part of their attribute. 

Though currently 'id' exists as a unique value across all service assets, this is not human readable as arn.  Arn would give out the region, service , account_id , aws_partition and the asset (all in one key). It will be easier to relate in case any other tool / script which depends on scoutsuite results would want to give out a report with list of assets and it's corresponding issues.

**Comment by j4v** [comment]
We should indeed include the ARN whenever they exist (sloppiness on out part). If you can provide the list of instances where it's missing that would be most helpful.

**Comment by rams3sh** [comment]
Please find the list of services along with relevant assets , that does not currently have arns as part of their asset info. This was gathered based on the output from my environment. Also efs, emr and directconnect was not being used in my evironment , hence that was not analysed, though this can be done with basic source code review.  This was done with ScoutSuite version 5.3.3. So any other updates added as part of it will not be present in the below list.

```
            awslambda:
                asset:
                    function:
            cloudformation:
                asset:
                    stack:
            ec2:
                asset:
                  snapshot:
                  volume:
                  image:
                  instance:
                  network_interface:
                  security_group:
            elasticache:
                asset:
                  cluster:
            elb:
                asset:
                  loadbalancer:
            rds:
                asset:
                  instance:
            redshift:
                asset:
                  cluster:
                  parameter_group:

            route53 :
                asset:
                  domain:
            s3:
                asset:
                  bucket:
            ses:
                asset:
                  identity:
            vpc:
                asset:
                    vpc
```
